apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
  namespace: librechat
data:
  librechat.yaml: |
    version: 1.0.8

    cache: true

    interface:
      # Privacy policy settings
      privacyPolicy:
        externalUrl: 'https://librechat.ai/privacy-policy'
        openNewTab: true

      # Terms of service
      termsOfService:
        externalUrl: 'https://librechat.ai/tos'
        openNewTab: true

    registration:
      socialLogins: [ "google" ]
    endpoints:
      custom:
        - name: "AI Gateway"
          apiKey: "not-needed"
          baseURL: "http://ai-gateway-litellm.showcase-news:4000"
          models:
            default: [ "gemini/gemini-2.5-flash" ]
            fetch: true
          titleConvo: true
          titleModel: "gemini/gemini-2.5-flash"
          summarize: false
          summaryModel: "gemini/gemini-2.5-flash"
          forcePrompt: false
          modelDisplayLabel: "Agentic Layer AI Gateway"
        - name: "Agent Gateway - news-agent"
          apiKey: "not-needed"
          baseURL: "http://agent-gateway.showcase-news:10000/news-agent"
          models:
            default: [ "news-agent" ]
            fetch: false
          titleConvo: false
          summarize: false
          forcePrompt: false
          addParams:
            # Agent Gateway does not support streaming yet
            disableStreaming: true

